// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateModZip(arg1:string,arg2:string,arg3:Array<main.CategoryConfig>,arg4:Array<string>,arg5:Array<string>):Promise<string>;

export function GetDefaultCategories():Promise<Array<main.CategoryConfig>>;

export function OpenGitHub():Promise<void>;

export function OpenNexusMod():Promise<void>;

export function PreviewPatchFile(arg1:string):Promise<number>;

export function SelectGameFolder():Promise<string>;

export function SelectPatchFile():Promise<string>;
