// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateModZip(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['CreateModZip'](arg1, arg2, arg3, arg4, arg5);
}

export function GetDefaultCategories() {
  return window['go']['main']['App']['GetDefaultCategories']();
}

export function OpenGitHub() {
  return window['go']['main']['App']['OpenGitHub']();
}

export function OpenNexusMod() {
  return window['go']['main']['App']['OpenNexusMod']();
}

export function PreviewPatchFile(arg1) {
  return window['go']['main']['App']['PreviewPatchFile'](arg1);
}

export function SelectGameFolder() {
  return window['go']['main']['App']['SelectGameFolder']();
}

export function SelectPatchFile() {
  return window['go']['main']['App']['SelectPatchFile']();
}
